# Site settings
title: Mility
email: zetsu@domain.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: ""
url: "http://mility.github.io/"

author:
  name     : 'Mility'
  email    : zhangmingju1992@foxmail.com
  url      : http://mility.github.io/
  #facebook : http://facebook.com/fernando.dev
  #twitter  : http://twitter.com/nandomoreirame

github: https://github.com/Mility
disqus_shortname: "Mility"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
