# Site settings
title: Mility
email: zhangmingju1992@live.com
description: A personal blog
baseurl: ""
url: "http://mility.github.io/"

author:
  name     : 'Mility'
  email    : zhangmingju@chinamobile.com
  #url      : http://mility.github.io/
  weibo: http://weibo.com/u/2145667551?is_all=1   #新浪微博
  facebook : http://facebook.com/Magee Zhang
  twitter  : http://twitter.com/@magee_zhang

github: https://github.com/Mility
disqus_shortname: "Mility"
#google_analytics: UA-52446115-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
