# Site settings
title: Mility
email: zhangmingju1992@foxmail.com
description: This is where I will tell my friends way too much about me
baseurl: ""
url: "http://mility.github.io/"

author:
  name     : 'Mility'
  email    : zhangmingju1992@live.com
  #url      : http://mility.github.io/
  weibo: http://weibo.com/u/2145667551?is_all=1   #新浪微博
  facebook : http://facebook.com/Mility
  #twitter  : http://twitter.com/nandomoreirame

github: https://github.com/Mility
disqus_shortname: "Mility"
#google_analytics: UA-52446115-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
